In [51]:
import pandas as pd
import numpy as np

In [52]:
data = pd.read_csv("banknotes.csv")

print(data.head(10))

   variance  skewness  curtosis  entropy  class
0   3.62160    8.6661  -2.80730 -0.44699      0
1   4.54590    8.1674  -2.45860 -1.46210      0
2   3.86600   -2.6383   1.92420  0.10645      0
3   3.45660    9.5228  -4.01120 -3.59440      0
4   0.32924   -4.4552   4.57180 -0.98880      0
5   4.36840    9.6718  -3.96060 -3.16250      0
6   3.59120    3.0129   0.72888  0.56421      0
7   2.09220   -6.8100   8.46360 -0.60216      0
8   3.20320    5.7588  -0.75345 -0.61251      0
9   1.53560    9.1772  -2.27180 -0.73535      0


In [53]:
print(data.shape)

print(data.describe())

(1372, 5)
          variance     skewness     curtosis      entropy        class
count  1372.000000  1372.000000  1372.000000  1372.000000  1372.000000
mean      0.433735     1.922353     1.397627    -1.191657     0.444606
std       2.842763     5.869047     4.310030     2.101013     0.497103
min      -7.042100   -13.773100    -5.286100    -8.548200     0.000000
25%      -1.773000    -1.708200    -1.574975    -2.413450     0.000000
50%       0.496180     2.319650     0.616630    -0.586650     0.000000
75%       2.821475     6.814625     3.179250     0.394810     1.000000
max       6.824800    12.951600    17.927400     2.449500     1.000000


In [54]:
X = data.iloc[:, :-1]
y = data.iloc[:, -1]

print(X.head())
print(y.head())

   variance  skewness  curtosis  entropy
0   3.62160    8.6661   -2.8073 -0.44699
1   4.54590    8.1674   -2.4586 -1.46210
2   3.86600   -2.6383    1.9242  0.10645
3   3.45660    9.5228   -4.0112 -3.59440
4   0.32924   -4.4552    4.5718 -0.98880
0    0
1    0
2    0
3    0
4    0
Name: class, dtype: int64


In [55]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

print("Training data shape:", x_train.shape)
print("Testing data shape:", x_test.shape)

Training data shape: (1097, 4)
Testing data shape: (275, 4)


In [56]:
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix, classification_report

In [57]:
mlp = MLPClassifier(max_iter=500, activation='relu')


mlp.fit(x_train, y_train)


pred = mlp.predict(x_test)


print("Confusion Matrix (ReLU):")
print(confusion_matrix(y_test, pred))

print("Classification Report (ReLU):")
print(classification_report(y_test, pred))

Confusion Matrix (ReLU):
[[154   0]
 [  0 121]]
Classification Report (ReLU):
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       154
           1       1.00      1.00      1.00       121

    accuracy                           1.00       275
   macro avg       1.00      1.00      1.00       275
weighted avg       1.00      1.00      1.00       275



In [58]:
mlp = MLPClassifier(max_iter=500, activation='logistic')
mlp.fit(x_train, y_train)

pred = mlp.predict(x_test)

print("Confusion Matrix (Logistic):")
print(confusion_matrix(y_test, pred))

print("Classification Report (Logistic):")
print(classification_report(y_test, pred))

Confusion Matrix (Logistic):
[[154   0]
 [  0 121]]
Classification Report (Logistic):
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       154
           1       1.00      1.00      1.00       121

    accuracy                           1.00       275
   macro avg       1.00      1.00      1.00       275
weighted avg       1.00      1.00      1.00       275



In [59]:
mlp = MLPClassifier(max_iter=500, activation='logistic')
mlp.fit(x_train, y_train)

pred = mlp.predict(x_test)

print("Confusion Matrix (Logistic):")
print(confusion_matrix(y_test, pred))

print("Classification Report (Logistic):")
print(classification_report(y_test, pred))

Confusion Matrix (Logistic):
[[154   0]
 [  0 121]]
Classification Report (Logistic):
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       154
           1       1.00      1.00      1.00       121

    accuracy                           1.00       275
   macro avg       1.00      1.00      1.00       275
weighted avg       1.00      1.00      1.00       275



In [60]:
mlp = MLPClassifier(max_iter=500, activation='tanh')
mlp.fit(x_train, y_train)

pred = mlp.predict(x_test)

print("Confusion Matrix (Tanh):")
print(confusion_matrix(y_test, pred))

print("Classification Report (Tanh):")
print(classification_report(y_test, pred))

Confusion Matrix (Tanh):
[[154   0]
 [  0 121]]
Classification Report (Tanh):
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       154
           1       1.00      1.00      1.00       121

    accuracy                           1.00       275
   macro avg       1.00      1.00      1.00       275
weighted avg       1.00      1.00      1.00       275



In [61]:
mlp = MLPClassifier(max_iter=500, activation='identity')
mlp.fit(x_train, y_train)

pred = mlp.predict(x_test)

print("Confusion Matrix (Identity):")
print(confusion_matrix(y_test, pred))

print("Classification Report (Identity):")
print(classification_report(y_test, pred))

Confusion Matrix (Identity):
[[152   2]
 [  1 120]]
Classification Report (Identity):
              precision    recall  f1-score   support

           0       0.99      0.99      0.99       154
           1       0.98      0.99      0.99       121

    accuracy                           0.99       275
   macro avg       0.99      0.99      0.99       275
weighted avg       0.99      0.99      0.99       275

